import { createContext, useContext, useEffect, useMemo, useRef, useState } from 'react'
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { yupResolver } from '@hookform/resolvers/yup'
import { useForm } from 'react-hook-form'
import { ArrowRight, Check, Heart, Minus, Plus, ShoppingBag, Sparkles, Truck, UserRound, X } from 'lucide-react'
import toast, { Toaster } from 'react-hot-toast'
import * as yup from 'yup'
import { BrowserMultiFormatReader } from '@zxing/browser'
import './App.css'

const API_URL = process.env.VITE_API_URL || 'https://fakestoreapi.com/products'
const USD_TO_INR = 83
const ADMIN_EMAIL = 'admin@indoforgien.com'
const ADMIN_PASSWORD = 'IndoAdmin@123'
const formatInr = (amount) => `₹${Math.round(amount * USD_TO_INR).toLocaleString('en-IN')}`
const AuthContext = createContext(null)
const CartContext = createContext(null)
function useAuth() { return useContext(AuthContext) }
function useCart() { return useContext(CartContext) }

function Providers({ children }) {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('bharthpe-user') || 'null'))
  const [cart, setCart] = useState(() => JSON.parse(localStorage.getItem('bharthpe-cart') || '[]'))
  useEffect(() => localStorage.setItem('bharthpe-user', JSON.stringify(user)), [user])
  useEffect(() => localStorage.setItem('bharthpe-cart', JSON.stringify(cart)), [cart])
  const auth = useMemo(() => ({ user, login: (email, password) => setUser({ email, admin: email.toLowerCase() === ADMIN_EMAIL && password === ADMIN_PASSWORD }), logout: () => { setUser(null); toast.success('You are signed out') } }), [user])
  const cartValue = useMemo(() => ({
    cart,
    addToCart: (product) => setCart((current) => { const existing = current.find((item) => item.id === product.id); toast.success(existing ? 'Quantity updated' : 'Added to your bag'); return existing ? current.map((item) => item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item) : [...current, { ...product, quantity: 1 }] }),
    updateQuantity: (id, quantity) => setCart((current) => quantity < 1 ? current.filter((item) => item.id !== id) : current.map((item) => item.id === id ? { ...item, quantity } : item)),
    removeFromCart: (id) => setCart((current) => current.filter((item) => item.id !== id)),
    clearCart: () => setCart([]),
  }), [cart])
  return <AuthContext.Provider value={auth}><CartContext.Provider value={cartValue}>{children}</CartContext.Provider></AuthContext.Provider>
}

function App() { return <BrowserRouter><Providers><Toaster position="top-right" toastOptions={{ duration: 2600 }} /><AppShell /></Providers></BrowserRouter> }

function AppShell() {
  const { user } = useAuth(); const { cart } = useCart(); const location = useLocation(); const [menuOpen, setMenuOpen] = useState(false)
  const cartCount = cart.reduce((total, item) => total + item.quantity, 0)

  return (
    <div className="app-shell"><div className="announcement"><Truck size={14} /> Complimentary delivery on orders over ₹6,225</div><header className="site-header"><Link to="/" className="brand">Indo<span>Forgien</span></Link><nav className={menuOpen ? 'main-nav open' : 'main-nav'}><Link className={location.pathname === '/' ? 'active' : ''} to="/">Shop all</Link><Link to="/scanner">Scan item</Link><a href="#women">Women</a></nav><div className="header-actions"><Link aria-label="Account" to={user ? '/orders' : '/login'}><UserRound size={19} /></Link><Link className="bag-link" to="/cart" aria-label="Shopping bag"><ShoppingBag size={19} /><span>{cartCount}</span></Link><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X size={20} /> : <span>Menu</span>}</button></div></header><main><Routes><Route path="/" element={<Home />} /><Route path="/login" element={<Login />} /><Route path="/cart" element={<Cart />} /><Route path="/checkout" element={<ProtectedRoute><Checkout /></ProtectedRoute>} /><Route path="/payment" element={<ProtectedRoute><Payment /></ProtectedRoute>} /><Route path="/scanner" element={<Scanner />} /><Route path="/orders" element={<ProtectedRoute><Orders /></ProtectedRoute>} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></main><footer><div className="footer-brand"><Link to="/" className="brand">Indo<span>Forgien</span></Link><p>Useful objects for a considered everyday.</p></div><div><small>Explore</small><Link to="/scanner">Scan an item</Link><a href="#women">Women</a><a href="mailto:hello@bharthpe.store">Contact</a></div><div><small>Stay in the loop</small><p>New drops, thoughtful notes, no noise.</p><form onSubmit={(event) => { event.preventDefault(); toast.success('You are on the list') }}><input aria-label="Email address" type="email" placeholder="Email address" required /><button aria-label="Subscribe"><ArrowRight size={18} /></button></form></div></footer></div>
  )
}

function ProtectedRoute({ children }) { return useAuth().user ? children : <Navigate to="/login" replace /> }
function useProducts() { const [state, setState] = useState({ products: [], loading: true, error: '' }); useEffect(() => { let active = true; const loadProducts = () => fetch(API_URL).then((response) => { if (!response.ok) throw new Error('Unable to reach the product service'); return response.json() }).then((products) => { const customProducts = JSON.parse(localStorage.getItem('indoforgien-products') || '[]'); if (active) setState({ products: [...customProducts, ...products], loading: false, error: '' }) }).catch((error) => active && setState({ products: [], loading: false, error: error.message })); loadProducts(); const refresh = () => loadProducts(); window.addEventListener('products-updated', refresh); return () => { active = false; window.removeEventListener('products-updated', refresh) } }, []); return state }

function Home() { const { products, loading, error } = useProducts(); const womenProducts = products.filter((product) => product.category?.toLowerCase().includes("women's clothing")); return <><section className="hero-section"><div className="hero-copy"><p className="eyebrow"><Sparkles size={14} /> Spring / summer 2026</p><h1>Make room for<br /><em>better</em> things.</h1><p className="hero-intro">Everyday objects with a little more thought in them. Designed to be used, kept, and loved.</p><a href="#collection" className="button dark">Explore the collection <ArrowRight size={16} /></a></div><div className="hero-art"><div className="fashion-figure woman-figure"><div className="figure-head" /><div className="figure-body" /></div><div className="fashion-figure man-figure"><div className="figure-head" /><div className="figure-body" /></div><div className="sun-disc" /><span>01 / 04</span></div></section><section className="collection" id="collection"><div className="section-heading"><div><p className="eyebrow">The edit</p><h2>Objects of affection</h2></div><p>Small upgrades for the spaces and rituals that make up your day.</p></div>{loading && <div className="status">Gathering the collection...</div>}{error && <div role="alert" className="status error">{error}. Please refresh and try again.</div>}{!loading && !error && <div className="product-grid">{products.slice(0, 6).map((product, index) => <ProductCard key={product.id} product={product} index={index} />)}</div>}</section>{!loading && !error && <section className="collection women-collection" id="women"><div className="section-heading"><div><p className="eyebrow">For her, for now</p><h2>Women’s collection</h2></div><p>Easy pieces and everyday layers chosen for a life in motion.</p></div><div className="product-grid">{womenProducts.slice(0, 3).map((product, index) => <ProductCard key={product.id} product={product} index={index + 1} />)}</div>{womenProducts.length === 0 && <div className="status">The women’s edit is arriving soon.</div>}</section>}</> }
function ProductCard({ product, index }) { const { addToCart } = useCart(); return <article className="product-card"><div className={'product-image tone-' + (index % 3)}><img src={product.image} alt={product.title} /><button aria-label={'Save ' + product.title}><Heart size={17} /></button></div><div className="product-meta"><div><h3>{product.title}</h3><p>{['Kitchen / Utility', 'Home / Ritual', 'Desk / Daily'][index % 3]}</p></div><strong>{formatInr(product.price)}</strong></div><button className="add-button" onClick={() => addToCart(product)}>Add to bag <Plus size={15} /></button></article> }

const loginSchema = yup.object({ email: yup.string().email('Enter a valid email address').required('Email is required'), password: yup.string().min(6, 'Use at least 6 characters').required('Password is required') })
function Login() { const { user, login } = useAuth(); const navigate = useNavigate(); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm({ resolver: yupResolver(loginSchema) }); if (user) return <Navigate to="/orders" replace />; const onSubmit = (data) => { login(data.email, data.password); toast.success(data.email.toLowerCase() === ADMIN_EMAIL && data.password === ADMIN_PASSWORD ? 'Admin access enabled' : 'Welcome back'); navigate('/orders') }; return <section className="form-page"><div className="form-intro"><p className="eyebrow">Welcome back</p><h1>Your good things<br /><em>are waiting.</em></h1><p>Sign in to check out, see your orders, and keep your saved pieces close.</p></div><form className="auth-form" onSubmit={handleSubmit(onSubmit)}><label>Email address<input type="email" {...register('email')} placeholder="you@example.com" />{errors.email && <span className="field-error">{errors.email.message}</span>}</label><label>Password<input type="password" {...register('password')} placeholder="At least 6 characters" />{errors.password && <span className="field-error">{errors.password.message}</span>}</label><button className="button dark full" disabled={isSubmitting}>Sign in <ArrowRight size={16} /></button><p className="form-note">Demo admin: {ADMIN_EMAIL} / {ADMIN_PASSWORD}</p></form></section> }
function Cart() { const { cart, updateQuantity, removeFromCart } = useCart(); const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0); return <section className="cart-page"><div className="page-heading"><p className="eyebrow">Your selections</p><h1>The bag</h1></div>{cart.length === 0 ? <div className="empty-state"><ShoppingBag size={35} /><h2>Your bag is waiting.</h2><p>Find something useful for the everyday.</p><Link to="/" className="button dark">Shop the edit <ArrowRight size={16} /></Link></div> : <div className="cart-layout"><div className="cart-items">{cart.map((item) => <div className="cart-item" key={item.id}><img src={item.image} alt="" /><div className="cart-item-info"><h3>{item.title}</h3><p>{formatInr(item.price)}</p><div className="quantity"><button onClick={() => updateQuantity(item.id, item.quantity - 1)} aria-label="Decrease quantity"><Minus size={14} /></button><span>{item.quantity}</span><button onClick={() => updateQuantity(item.id, item.quantity + 1)} aria-label="Increase quantity"><Plus size={14} /></button></div></div><button className="remove" onClick={() => removeFromCart(item.id)} aria-label={'Remove ' + item.title}><X size={17} /></button></div>)}</div><aside className="summary"><p className="eyebrow">Order summary</p><div><span>Subtotal</span><strong>{formatInr(subtotal)}</strong></div><div><span>Delivery</span><span>Complimentary</span></div><hr /><div className="total"><span>Total</span><strong>{formatInr(subtotal)}</strong></div><Link to="/checkout" className="button dark full">Continue to checkout <ArrowRight size={16} /></Link></aside></div>}</section> }
const checkoutSchema = yup.object({ name: yup.string().required('Name is required'), address: yup.string().required('Address is required'), city: yup.string().required('City is required'), zip: yup.string().matches(/^\d{5,6}$/, 'Enter a valid postal code').required('Postal code is required') })
function Checkout() { const { cart } = useCart(); const navigate = useNavigate(); const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm({ resolver: yupResolver(checkoutSchema) }); if (!cart.length) return <Navigate to="/" replace />; const submit = () => { toast.success('Address saved'); navigate('/payment') }; return <section className="form-page checkout-page"><div className="form-intro"><p className="eyebrow">Almost yours</p><h1>Make it<br /><em>official.</em></h1><p>We will send your order confirmation and delivery updates to your account email.</p></div><form className="auth-form" onSubmit={handleSubmit(submit)}><label>Full name<input {...register('name')} placeholder="Your name" />{errors.name && <span className="field-error">{errors.name.message}</span>}</label><label>Street address<input {...register('address')} placeholder="12 Example Street" />{errors.address && <span className="field-error">{errors.address.message}</span>}</label><div className="form-row"><label>City<input {...register('city')} placeholder="Mumbai" />{errors.city && <span className="field-error">{errors.city.message}</span>}</label><label>Postal code<input {...register('zip')} placeholder="400001" />{errors.zip && <span className="field-error">{errors.zip.message}</span>}</label></div><button className="button dark full" disabled={isSubmitting}>Continue to payment <ArrowRight size={16} /></button></form></section> }

function Payment() { const { cart, clearCart } = useCart(); const navigate = useNavigate(); const [method, setMethod] = useState('upi'); const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0); if (!cart.length) return <Navigate to="/" replace />; const placeOrder = (event) => { event.preventDefault(); clearCart(); toast.success('Payment successful. Order placed!'); navigate('/orders') }; return <section className="payment-page"><div className="page-heading"><p className="eyebrow">Step 2 of 2</p><h1>Choose payment.</h1></div><div className="payment-layout"><form className="payment-methods" onSubmit={placeOrder}><fieldset><legend>Payment method</legend><label className="payment-option"><input type="radio" name="payment" checked={method === 'upi'} onChange={() => setMethod('upi')} /> <span><strong>UPI</strong><small>Google Pay, PhonePe, Paytm</small></span></label><label className="payment-option"><input type="radio" name="payment" checked={method === 'card'} onChange={() => setMethod('card')} /> <span><strong>Card</strong><small>Credit or debit card</small></span></label><label className="payment-option"><input type="radio" name="payment" checked={method === 'cod'} onChange={() => setMethod('cod')} /> <span><strong>Cash on delivery</strong><small>Pay when your order arrives</small></span></label></fieldset>{method !== 'cod' && <input className="payment-input" placeholder={method === 'upi' ? 'yourname@upi' : 'Card number'} aria-label={method === 'upi' ? 'UPI ID' : 'Card number'} required />}{method === 'card' && <div className="form-row"><input className="payment-input" placeholder="MM / YY" aria-label="Expiry date" required /><input className="payment-input" placeholder="CVV" aria-label="CVV" required /></div>}<button className="button dark full" type="submit">Pay {formatInr(total)} <Check size={16} /></button></form><aside className="summary"><p className="eyebrow">Order total</p><div><span>Items</span><strong>{formatInr(total)}</strong></div><div><span>Delivery</span><span>Free</span></div><hr /><div className="total"><span>Payable</span><strong>{formatInr(total)}</strong></div><p className="secure-note">Your payment details are handled securely.</p></aside></div></section> }

function Scanner() { const [scanning, setScanning] = useState(false); const [codes, setCodes] = useState([]); const [message, setMessage] = useState('Use your camera to scan a product barcode or QR code.'); const videoRef = useRef(null); const readerRef = useRef(null); const startScanner = async () => { setScanning(true); setMessage('Point your camera at a barcode or QR code.'); readerRef.current = new BrowserMultiFormatReader(); try { await readerRef.current.decodeFromVideoDevice(undefined, videoRef.current, (result) => { if (!result) return; const value = result.getText(); setCodes((current) => { if (current.includes(value)) { setMessage(`Duplicate found: ${value}`); toast.error('Duplicate item detected'); return current } setMessage(`Scanned: ${value}`); toast.success('New item scanned'); return [...current, value] }) }) } catch { setScanning(false); setMessage('Camera access was unavailable. Check browser permissions or use a device with a camera.') } }; const stopScanner = () => { readerRef.current?.reset(); setScanning(false); setMessage('Scanner paused.'); }; useEffect(() => () => readerRef.current?.reset(), []); return <section className="scanner-page"><div className="page-heading"><p className="eyebrow">Smart shopping</p><h1>Scan &amp; check.</h1><p className="scanner-intro">Scan each item before you add it. IndoForgien will flag a repeated barcode so you do not accidentally buy twice.</p></div><div className="scanner-layout"><div className="scanner-box"><video ref={videoRef} className={scanning ? 'camera-view active' : 'camera-view'} aria-label="Live camera preview" autoPlay muted playsInline />{!scanning && <div className="camera-placeholder"><ShoppingBag size={36} /><p>Camera preview</p></div>}<div className="scanner-controls">{scanning ? <button className="button dark" onClick={stopScanner}><X size={16} /> Stop camera</button> : <button className="button dark" onClick={startScanner}><span aria-hidden="true">◎</span> Start camera</button>}<p role="status" aria-live="polite">{message}</p></div></div><aside className="scan-results"><p className="eyebrow">Scanned items</p><h2>{codes.length} unique</h2>{codes.length === 0 ? <p className="muted">No items scanned yet.</p> : <ul>{codes.map((code) => <li key={code}><Check size={15} />{code}</li>)}</ul>}<button className="text-link" onClick={() => { setCodes([]); setMessage('Scan list cleared.') }}>Clear list <X size={15} /></button></aside></div></section> }
function Admin() { const [title, setTitle] = useState(''); const [price, setPrice] = useState(''); const [category, setCategory] = useState("women's clothing"); const [image, setImage] = useState('https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=700&q=80'); const addProduct = (event) => { event.preventDefault(); const product = { id: `admin-${Date.now()}`, title, price: Number(price) / USD_TO_INR, category, image }; const current = JSON.parse(localStorage.getItem('indoforgien-products') || '[]'); localStorage.setItem('indoforgien-products', JSON.stringify([product, ...current])); window.dispatchEvent(new Event('products-updated')); setTitle(''); setPrice(''); toast.success('Item added to the collection') }; return <section className="admin-page"><div className="page-heading"><p className="eyebrow">Admin studio</p><h1>Add new things.</h1><p className="scanner-intro">Create future products for the Women’s or Men’s collection. Prices are entered in Indian rupees.</p></div><form className="admin-form" onSubmit={addProduct}><label>Item name<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Silk evening shirt" required /></label><label>Price in rupees<input type="number" min="1" value={price} onChange={(event) => setPrice(event.target.value)} placeholder="4999" required /></label><label>Collection<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="women's clothing">Women</option><option value="men's clothing">Men</option></select></label><label>Image URL<input value={image} onChange={(event) => setImage(event.target.value)} type="url" required /></label><button className="button dark" type="submit">Add item <Plus size={16} /></button></form></section> }
function Orders() { const { user, logout } = useAuth(); if (user.admin) return <><Admin /><section className="admin-footer"><button className="text-link" onClick={logout}>Sign out <ArrowRight size={15} /></button></section></>; return <section className="orders-page"><div className="page-heading"><p className="eyebrow">Your account</p><h1>Hello, {user.email.split('@')[0]}.</h1><button className="text-link" onClick={logout}>Sign out <ArrowRight size={15} /></button></div><div className="order-card"><div className="order-top"><span>Order history</span><span>Account email: {user.email}</span></div><div className="empty-state compact"><Check size={28} /><h2>Your orders will appear here.</h2><p>Take a look around and find something worth keeping.</p><Link to="/" className="text-link">Continue shopping <ArrowRight size={15} /></Link></div></div></section> }

export default App
